<template><section class="area-editor"><header><strong>图片区 {{ area.id }}</strong><div><el-button size="small" @click="$emit('append-crops')">追加裁图</el-button><el-button size="small" :disabled="!selected" @click="$emit('restore-natural',selected)">恢复自然尺寸</el-button><el-button size="small" type="danger" plain :disabled="!selected" @click="$emit('remove-figure',selected)">删除配图</el-button></div></header><div ref="stage" class="stage"><QuestionImageAreaCanvas :area="area" :url-for="urlFor" :selected-figure-id="selected"><template #overlay="{placement}"><button class="hit" type="button" :aria-label="`移动配图 ${placement.figure_id}`" @pointerdown.stop="start($event,placement,'move')" @click.stop="selected=placement.figure_id"><i class="resize" @pointerdown.stop="start($event,placement,'resize')"></i></button></template></QuestionImageAreaCanvas></div><footer><label>高度比例 <el-input-number :model-value="area.height_ratio" :min="0.05" :step="0.05" :precision="3" size="small" @change="$emit('set-height',$event)" /></label><el-select v-model="targetSection" size="small" placeholder="移动到其他区段"><el-option v-for="option in targetOptions" :key="option.value" :label="option.label" :value="option.value" /></el-select><el-button size="small" :disabled="!targetSection" @click="$emit('move-area',targetSection)">移动图片区</el-button><el-button size="small" type="danger" plain @click="$emit('remove-area')">删除图片区</el-button></footer></section></template>
<script setup>
import {computed,onBeforeUnmount,ref} from 'vue';import QuestionImageAreaCanvas from './QuestionImageAreaCanvas.vue'
const props=defineProps({area:{type:Object,required:true},section:{type:String,required:true},canvasWidth:{type:Number,required:true},urlFor:{type:Function,required:true}});const emit=defineEmits(['append-crops','placement-change','restore-natural','remove-figure','set-height','move-area','remove-area'])
const stage=ref(),selected=ref(''),targetSection=ref('');let operation=null
const sections=[{value:'stem',label:'题干'},{value:'answer',label:'答案'},{value:'analysis',label:'解析'}];const targetOptions=computed(()=>sections.filter((item)=>item.value!==props.section))
const point=(event)=>{const rect=stage.value.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width*props.canvasWidth,y:(event.clientY-rect.top)/rect.width*props.canvasWidth}}
const toRect=(placement)=>{const height=props.canvasWidth*props.area.height_ratio;return{left:placement.x*props.canvasWidth,top:placement.y*height,width:placement.width*props.canvasWidth,height:placement.height*height}}
const start=(event,placement,type)=>{if(event.button!==0)return;selected.value=placement.figure_id;operation={type,figureId:placement.figure_id,start:point(event),rect:toRect(placement)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',finish);window.addEventListener('pointercancel',cancel)}
const move=(event)=>{if(!operation)return;const p=point(event),dx=p.x-operation.start.x,dy=p.y-operation.start.y;if(operation.type==='move')operation.candidate={...operation.rect,left:operation.rect.left+dx,top:operation.rect.top+dy};else{const ratio=operation.rect.width/operation.rect.height;const width=Math.max(8,operation.rect.width+dx);operation.candidate={...operation.rect,width,height:width/ratio}}}
const cleanup=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',finish);window.removeEventListener('pointercancel',cancel)};const finish=()=>{if(operation?.candidate)emit('placement-change',operation.figureId,operation.candidate);operation=null;cleanup()};const cancel=()=>{operation=null;cleanup()};onBeforeUnmount(cleanup)
</script>
<style scoped>.area-editor{display:grid;gap:10px}.area-editor header,.area-editor footer{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.area-editor header>div,.area-editor footer{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.stage{position:relative}.hit{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent;cursor:move}.resize{position:absolute;right:-5px;bottom:-5px;width:12px;height:12px;background:#fff;border:2px solid #409eff;cursor:nwse-resize}</style>
