import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
const dashboard = readFileSync(resolve(process.cwd(), 'src/views/Dashboard.vue'), 'utf8')
const editor = readFileSync(resolve(process.cwd(), 'src/components/QuestionSegmentationEditor.vue'), 'utf8')
const review = readFileSync(resolve(process.cwd(), 'src/components/QuestionBatchReview.vue'), 'utf8')
const failures = []
const requireMatch = (source, pattern, message) => { if (!pattern.test(source)) failures.push(message) }
requireMatch(dashboard, /label="batch">批量分题/, 'Dashboard must offer batch segmentation mode')
requireMatch(dashboard, /crop_bbox: job\.bbox/, 'Each batch Draft must use its own bbox')
requireMatch(dashboard, /QUESTION_RECOGNITION_CONCURRENCY/, 'Batch recognition must use the shared concurrency limit')
requireMatch(dashboard, /createConcurrencyGate\(QUESTION_RECOGNITION_CONCURRENCY\)/, 'All initial and retry recognition must share the max-2 concurrency gate')
requireMatch(dashboard, /isRecognizeTimeout\(error\)[\s\S]*reconcileBatchJob/, 'Timeouts must reconcile Draft status')
requireMatch(dashboard, /const returnToSegmentation = async \(\) =>/, 'Review must guard returning to segmentation')
requireMatch(dashboard, /hasRunning[\s\S]*hasUnsaved[\s\S]*ElMessageBox\.confirm/, 'Returning must confirm running work and unsaved ready Drafts')
requireMatch(dashboard, /:initial-boxes="batchJobs"/, 'Returning to segmentation must preserve the current boxes')
requireMatch(dashboard, /batchSourceAssetId\.value/, 'The page asset must be reused for all boxes')
requireMatch(dashboard, /createQuestionJobs\(boxes, batchJobs\.value\)/, 'Re-confirming must reuse unchanged Drafts instead of duplicating them')
requireMatch(dashboard, /job\.status !== 'saved_to_bank'/, 'Already-saved questions must be skipped on the next run')
requireMatch(dashboard, /error\.response\?\.status === 409[\s\S]*reconcileBatchJob/, 'A 409 already-recognizing response must reconcile instead of failing immediately')
if (/runLegacyRecognition\(.*job|uploadFullImage\(.*job/s.test(dashboard)) failures.push('Batch jobs must not fall back to full-page or legacy recognition')
requireMatch(editor, /aria-label="题目框选画布/, 'Segmentation canvas needs an accessible label')
requireMatch(editor, /aria-label="`删除第 \$\{index \+ 1\} 题框`"/, 'Box delete controls need specific accessible labels')
requireMatch(editor, /startMoving\(\$event, box\)/, 'Selected boxes must support pointer movement')
requireMatch(editor, /startResizing\(\$event, box\)/, 'Selected boxes must support resize handles')
requireMatch(editor, /moveBox\(index, -1\)/, 'Question list must support manual move-up ordering')
requireMatch(editor, /moveBox\(index, 1\)/, 'Question list must support manual move-down ordering')
requireMatch(editor, /sortReadingOrder/, 'Reading-order sorting must be an explicit control')
requireMatch(editor, /\['Delete', 'Backspace'\]/, 'Selected boxes must support keyboard deletion')
requireMatch(editor, /HTMLInputElement[\s\S]*HTMLTextAreaElement[\s\S]*isContentEditable/, 'Keyboard deletion must not hijack text inputs')
requireMatch(review, /buildDraftImageUrl\(job\.draftId\)/, 'Each ready Draft must load its authenticated cropped reference image')
requireMatch(review, /<figure-overlay-editor/, 'Each detected figure result must provide the existing figure overlay editor')
requireMatch(review, /@update:model-value="\$emit\('update-figure', job, \$event\)"/, 'Figure bbox selection must update the owning job')
requireMatch(review, /v-else-if="job\.status === 'failed'"/, 'Retry must only render for terminal failed jobs')
requireMatch(review, /@click="\$emit\('retry', job\)"/, 'Each job must support independent retry')
requireMatch(review, /@click="\$emit\('save-bank', job\)"/, 'Each job must support independent save')
requireMatch(review, /@click="\$emit\('edit', job\)"/, 'Each job must support independent editing')
if (failures.length) { console.error(failures.map((item) => `- ${item}`).join('\n')); process.exit(1) }
console.log('Question segmentation contract passed.')
