import assert from 'node:assert/strict'
import { createQuestionImageLoaderCore } from '../src/utils/questionImageLoaderCore.mjs'
import { boundedGet } from '../src/utils/boundedRequest.mjs'
const flush = () => new Promise(resolve => setImmediate(resolve))
const requests = []
const revoked = []
const loader = createQuestionImageLoaderCore({
  http: { get: (url, options) => new Promise((resolve, reject) => requests.push({url, options, resolve, reject})) },
  urlApi: { createObjectURL: blob => `blob:${blob.id}`, revokeObjectURL: url => revoked.push(url) },
  buildImageUrl: id => `/image/${id}`, timeout: 20
})
const item = {id: 1, image_url: true}
loader.ensure(item)
assert.equal(loader.loadingFor(item), true)
const old = requests.shift()
loader.dispose()
assert.equal(old.options.signal.aborted, true)
loader.ensure(item)
const newer = requests.shift()
old.resolve({data: {id: 'old'}})
newer.resolve({data: {id: 'new'}})
await flush()
assert.equal(loader.imageUrlFor(item), 'blob:new', 'late response cannot replace reopened image')
assert.equal(loader.loadingFor(item), false)
loader.markFailed(item)
assert.ok(revoked.includes('blob:new'))
assert.match(loader.errorFor(item), /重试/)
loader.retry(item)
const timed = requests.shift()
await new Promise(resolve => setTimeout(resolve, 35))
assert.equal(timed.options.signal.aborted, true)
assert.equal(loader.loadingFor(item), false)
assert.match(loader.errorFor(item), /超时/)
timed.resolve({data: {id:'late-timeout'}})
await flush()
assert.equal(loader.imageUrlFor(item), '')
loader.retry(item)
requests.shift().resolve({data:{id:'recovered'}})
await flush()
assert.equal(loader.imageUrlFor(item), 'blob:recovered')
loader.syncItems([{...item,current_revision_no:1}])
loader.syncItems([{...item,current_revision_no:2}])
assert.ok(revoked.includes('blob:recovered'), 'revision changes invalidate a retained editor image')
requests.shift().reject(new Error('offline'))
await flush()
assert.match(loader.errorFor(item), /失败/)
loader.retry(item)
requests.shift().resolve({data:{id:'retry'}})
await flush()
loader.remove(item.id)
assert.ok(revoked.includes('blob:retry'))
loader.ensure({id:2})
assert.equal(requests.length,0,'imageless items do not request images')
loader.dispose()
await assert.rejects(boundedGet({get:()=>{throw new Error('sync failure')}}, '/list', {timeout:20}), /sync failure/)
const controller = new AbortController()
controller.abort()
let calls=0
await assert.rejects(boundedGet({get:()=>{calls++}}, '/list', {signal:controller.signal}), {code:'ERR_CANCELED'})
assert.equal(calls,0)
console.log('Question image loader timeout, retry, cancellation and isolation passed.')
