<template>
  <main class="question-editor-page">
    <header class="editor-header">
      <div><el-button @click="goBack">返回题库</el-button><strong>题目 #{{ questionId }}</strong><el-tag>Revision {{ revisionNo }}</el-tag><el-tag v-if="dirty" type="warning">未保存</el-tag></div>
      <div><el-button :disabled="!canUndo||saving" @click="undo">撤销</el-button><el-button :disabled="!canRedo||saving" @click="redo">重做</el-button><el-button :disabled="!dirty||saving" @click="discard">放弃修改</el-button><el-button type="primary" :loading="saving" :disabled="!canSave" @click="saveDocument">保存整个题目</el-button></div>
    </header>
    <el-alert v-if="loadError" :title="loadError" type="error" :closable="false" show-icon />
    <el-alert v-if="conflict" title="服务器已有更新；完整本地草稿、撤销历史和临时裁图预览均已保留。" type="warning" :closable="false" show-icon><el-button size="small" @click="reloadLatest">放弃本地并加载最新版</el-button></el-alert>
    <el-alert v-if="saveError" :title="saveError" type="error" :closable="false" show-icon />
    <el-skeleton v-if="loading" :rows="8" animated />
    <template v-else-if="draft">
      <el-radio-group v-model="mobilePane" class="mobile-switch"><el-radio-button value="content">编辑内容</el-radio-button><el-radio-button value="source">查看来源图</el-radio-button><el-radio-button value="preview">整题预览</el-radio-button></el-radio-group>
      <div class="editor-layout">
        <aside class="source-pane" :class="{'mobile-hidden':mobilePane!=='source'}">
          <h2>题目区域图</h2>
          <img v-if="sourceImageUrl" :src="sourceImageUrl" alt="题目区域图" class="source-image" @load="captureSourceSize" />
          <el-empty v-else description="暂无来源图" />
        </aside>
        <section class="content-pane" :class="{'mobile-hidden':mobilePane!=='content'}">
          <el-tabs v-model="activeSection" @tab-change="flushTextGesture"><el-tab-pane v-for="section in sectionOptions" :key="section.value" :label="section.label" :name="section.value" /></el-tabs>
          <div v-if="activeSection==='stem'" class="metadata-grid">
            <el-form-item label="知识点"><el-select :model-value="tagLabels" multiple filterable allow-create default-first-option @update:model-value="setTags" /></el-form-item>
            <el-form-item label="题型"><el-select :model-value="draft.metadata.question_type" clearable @update:model-value="setMetadata('question_type',$event)"><el-option v-for="item in questionTypes" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item>
            <el-form-item label="难度"><el-select :model-value="draft.metadata.difficulty_level" clearable @update:model-value="setMetadata('difficulty_level',$event)"><el-option label="未设置" :value="null"/><el-option v-for="level in 5" :key="level" :label="`${level} 星`" :value="level" /></el-select></el-form-item>
          </div>
          <QuestionDocumentErrorNavigator :errors="allErrors" @navigate="navigateError" />
          <div class="insertion"><el-button size="small" @click="addBlockAt(0)">在开头添加文字</el-button><el-button size="small" :disabled="!sourceReady" @click="openNewArea(0)">在开头添加图片区</el-button></div>
          <div class="block-list">
            <template v-for="(block,index) in activeBlocks" :key="block.id">
              <article class="block-card" :data-block-id="block.id">
                <template v-if="block.kind==='text'">
                  <div class="block-head"><strong>文字块 {{ index+1 }}</strong><small>{{ block.id }}</small></div>
                  <el-input :model-value="block.markdown" type="textarea" :autosize="{minRows:4,maxRows:16}" @focus="beginTextGesture(block.id)" @update:model-value="updateText(block.id,$event)" @blur="flushTextGesture" />
                  <div class="block-actions"><el-button size="small" :disabled="index===0" @click="move(block.id,index-1)">上移</el-button><el-button size="small" :disabled="index===activeBlocks.length-1" @click="move(block.id,index+1)">下移</el-button><el-button size="small" :disabled="activeBlocks[index+1]?.kind!=='text'" @click="merge(block.id)">与下一块合并</el-button><el-select v-model="moveTargets[block.id]" size="small" placeholder="移动到区段"><el-option v-for="item in otherSections" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-button size="small" @click="moveToSection(block.id)">移动</el-button><el-button size="small" type="danger" plain @click="removeText(block.id)">删除</el-button></div>
                  <div v-if="safeParagraphs(block.markdown).length>1" class="paragraph-actions"><el-select v-model="paragraphSelections[block.id]" size="small" placeholder="选择段落"><el-option v-for="paragraph in safeParagraphs(block.markdown)" :key="paragraph.index" :label="`第 ${paragraph.index+1} 段：${paragraph.excerpt}`" :value="paragraph.index" /></el-select><el-button size="small" :disabled="paragraphSelections[block.id]>=safeParagraphs(block.markdown).length-1" @click="split(block.id)">在所选段落后拆分</el-button><el-select v-model="paragraphMoveTargets[block.id]" size="small" placeholder="段落移动到区段"><el-option v-for="item in otherSections" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-button size="small" @click="moveParagraph(block.id)">移动所选段落</el-button></div>
                  <div class="markdown-body block-preview" v-html="renderMarkdown(block.markdown)"></div>
                </template>
                <QuestionImageAreaEditor v-else :area="block" :section="activeSection" :canvas-width="canvasWidth" :url-for="figureUrlFor" @append-crops="openAppend(block.id)" @placement-change="(figureId,rect)=>changePlacement(block.id,figureId,rect)" @restore-natural="restoreNatural(block.id,$event)" @remove-figure="removeFigure(block.id,$event)" @set-height="changeHeight(block.id,$event)" @move-area="moveArea(block.id,$event)" @remove-area="removeArea(block.id)" />
              </article>
              <div class="insertion"><el-button size="small" @click="addBlockAt(index+1)">在此处添加文字</el-button><el-button size="small" :disabled="!sourceReady" @click="openNewArea(index+1)">在此处添加图片区</el-button></div>
            </template>
          </div>
          <div v-if="activeBlocks.length===0" class="empty-section"><el-empty :description="`${sectionLabel}暂无内容`" /></div>
        </section>
        <aside class="preview-pane" :class="{'mobile-hidden':mobilePane!=='preview'}"><h2>未保存草稿预览</h2><QuestionDraftPreview :draft="draft" :url-for="figureUrlFor" /></aside>
      </div>
    </template>
    <el-dialog v-model="cropDialog" title="从题目区域图裁取配图" width="min(920px, 96vw)" destroy-on-close @closed="cropBoxes=[]"><QuestionFigureCropOverlay v-if="sourceImageUrl" v-model="cropBoxes" :src="sourceImageUrl" /><template #footer><el-button @click="cropDialog=false">取消</el-button><el-button type="primary" :disabled="!cropCanConfirm" @click="confirmCrops">确认添加 {{ cropBoxes.length }} 张</el-button></template></el-dialog>
  </main>
</template>
<script setup>
import {computed,nextTick,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue'
import {onBeforeRouteLeave,useRoute,useRouter} from 'vue-router'
import axios from 'axios';import{ElMessage,ElMessageBox}from'element-plus'
import{API_V1_BASE_URL}from'../config/api';import{createQuestionImageLoader}from'../utils/questionImageLoader';import{createQuestionFigurePreviewRegistry}from'../utils/questionFigurePreviewRegistry.js';import{renderMarkdown}from'@/utils/renderMarkdown'
import QuestionFigureCropOverlay from '../components/QuestionFigureCropOverlay.vue';import QuestionImageAreaEditor from '../components/QuestionImageAreaEditor.vue';import QuestionDraftPreview from '../components/QuestionDraftPreview.vue';import QuestionDocumentErrorNavigator from '../components/QuestionDocumentErrorNavigator.vue'
import{addCropsToImageArea,addImageArea,addTextBlock,buildQuestionDocumentPayload,cloneQuestionDocument,createEditorSession,deleteImageArea,deleteTextBlock,editTextBlock,executeEditorCommand,findSafeMarkdownParagraphs,isQuestionDocumentDirty,mergeTextBlockWithNext,moveBlockToSection,moveParagraphToSection,reachableFigureIds,redoEditorSession,removeFigurePlacement,reorderBlock,resetEditorSession,restorePlacementNaturalSize,setImageAreaHeight,splitTextBlockAtParagraph,undoEditorSession,updatePlacement,validateQuestionDocumentDraft}from'../utils/questionDocumentEditorState.mjs'
const route=useRoute(),router=useRouter(),questionId=computed(()=>Number(route.params.id));const loading=ref(false),saving=ref(false),loadError=ref(''),saveError=ref(''),conflict=ref(false),revisionNo=ref(0),activeSection=ref('stem'),mobilePane=ref('content'),session=ref(null),serverErrors=ref([]),sourceSize=reactive({width:0,height:0}),cropDialog=ref(false),cropBoxes=ref([]),cropTarget=ref(null);let generation=0,textGesture=null
const paragraphSelections=reactive({}),paragraphMoveTargets=reactive({}),moveTargets=reactive({});const sectionOptions=[{value:'stem',label:'题干'},{value:'answer',label:'答案'},{value:'analysis',label:'解析'}],questionTypes=[{value:'single_choice',label:'单选题'},{value:'multiple_choice',label:'多选题'},{value:'fill_blank',label:'填空题'},{value:'solution',label:'解答题'},{value:'judge',label:'判断题'},{value:'unknown',label:'未知'}]
const loader=createQuestionImageLoader(),figureRegistry=createQuestionFigurePreviewRegistry(),draft=computed(()=>session.value?.present),baseline=computed(()=>session.value?.baseline),sourceImageUrl=computed(()=>loader.imageUrlFor(draft.value)),activeBlocks=computed(()=>draft.value?.sections?.[activeSection.value]?.blocks||[]),sectionLabel=computed(()=>sectionOptions.find(x=>x.value===activeSection.value)?.label),otherSections=computed(()=>sectionOptions.filter(item=>item.value!==activeSection.value)),dirty=computed(()=>isQuestionDocumentDirty(draft.value,baseline.value)),validation=computed(()=>validateQuestionDocumentDraft(draft.value)),allErrors=computed(()=>[...validation.value.errors,...serverErrors.value]),canSave=computed(()=>dirty.value&&validation.value.valid&&!saving.value),canUndo=computed(()=>Boolean(session.value?.past.length||textGesture)),canRedo=computed(()=>Boolean(session.value?.future.length)),canvasWidth=computed(()=>sourceSize.width||1000),sourceReady=computed(()=>sourceSize.width>0&&sourceSize.height>0),tagLabels=computed(()=>draft.value?.metadata.knowledge_tags.map(tag=>tag.label)||[]),cropCanConfirm=computed(()=>cropBoxes.value.length>0&&cropBoxes.value.every(box=>box[2]*box[3]>=.01))
const figureUrlFor=(id)=>figureRegistry.urlFor(id);const captureSourceSize=(event)=>{sourceSize.width=event.target.naturalWidth;sourceSize.height=event.target.naturalHeight;syncFigures()}
const syncFigures=()=>{if(!session.value)return;figureRegistry.reconcile({questionId:questionId.value,figures:draft.value.figures,reachableIds:reachableFigureIds(session.value),source:{url:sourceImageUrl.value,generation,width:sourceSize.width,height:sourceSize.height}})}
const applyDocument=(doc)=>{session.value=createEditorSession(doc);revisionNo.value=doc.current_revision_no;loader.syncItems([doc]);conflict.value=false;saveError.value='';serverErrors.value=[];sourceSize.width=0;sourceSize.height=0;nextTick(syncFigures)}
const loadDocument=async()=>{if(!Number.isInteger(questionId.value)||questionId.value<=0){loadError.value='题目编号无效';return}const token=++generation;loading.value=true;loadError.value='';try{const response=await axios.get(`${API_V1_BASE_URL}/questions/${questionId.value}/document`);if(token===generation)applyDocument(response.data)}catch(error){if(token===generation)loadError.value=typeof error.response?.data?.detail==='string'?error.response.data.detail:'加载题目失败'}finally{if(token===generation)loading.value=false}}
const execute=(operation)=>{flushTextGesture();const result=executeEditorCommand(session.value,operation);if(result.error)ElMessage.warning(result.error);if(result.changed){session.value=result.session;serverErrors.value=[];nextTick(syncFigures)}return result}
const beginTextGesture=()=>{if(!textGesture)textGesture=cloneQuestionDocument(draft.value)};const updateText=(id,text)=>{if(!textGesture)beginTextGesture();session.value={...session.value,present:editTextBlock(draft.value,activeSection.value,id,text).document,future:[]}}
const flushTextGesture=()=>{if(!textGesture||!session.value)return;const before=textGesture;textGesture=null;if(JSON.stringify(before)!==JSON.stringify(draft.value))session.value={...session.value,past:[...session.value.past,before].slice(-100),future:[]}}
const undo=()=>{flushTextGesture();session.value=undoEditorSession(session.value);syncFigures()};const redo=()=>{flushTextGesture();session.value=redoEditorSession(session.value);syncFigures()}
const setMetadata=(field,value)=>execute(document=>({document:{...cloneQuestionDocument(document),metadata:{...cloneQuestionDocument(document.metadata),[field]:value}},changed:true,error:null}));const setTags=(values)=>setMetadata('knowledge_tags',values.map(label=>({label,score:1})))
const addBlockAt=(index)=>execute(document=>addTextBlock(document,activeSection.value,{markdown:'请输入内容',index}));const move=(id,index)=>execute(document=>reorderBlock(document,activeSection.value,id,index));const merge=(id)=>execute(document=>mergeTextBlockWithNext(document,activeSection.value,id));const removeText=async(id)=>{try{await ElMessageBox.confirm('删除这个文字块？','确认',{type:'warning'});execute(document=>deleteTextBlock(document,activeSection.value,id))}catch{}};const safeParagraphs=findSafeMarkdownParagraphs;const split=(id)=>{if(!Number.isInteger(paragraphSelections[id]))return ElMessage.warning('请先选择拆分段落');execute(document=>splitTextBlockAtParagraph(document,activeSection.value,id,paragraphSelections[id]+1))};const moveToSection=(id)=>{const target=moveTargets[id];if(target)execute(document=>moveBlockToSection(document,activeSection.value,id,target))};const moveParagraph=(id)=>{const target=paragraphMoveTargets[id];if(!target||!Number.isInteger(paragraphSelections[id]))return ElMessage.warning('请选择段落和目标区段');execute(document=>moveParagraphToSection(document,activeSection.value,id,paragraphSelections[id],target))}
const openNewArea=(index)=>{cropTarget.value={section:activeSection.value,index,areaId:null};cropBoxes.value=[];cropDialog.value=true};const openAppend=(areaId)=>{cropTarget.value={section:activeSection.value,areaId};cropBoxes.value=[];cropDialog.value=true}
const confirmCrops=()=>{const target=cropTarget.value,bboxes=cloneQuestionDocument(cropBoxes.value);const areaId=target.areaId||crypto.randomUUID();const result=execute(document=>{let current=document;if(!target.areaId){const added=addImageArea(current,target.section,{index:target.index,createId:()=>areaId});if(added.error)return added;current=added.document}return addCropsToImageArea(current,areaId,bboxes,{canvasWidth:canvasWidth.value,sourceWidth:sourceSize.width,sourceHeight:sourceSize.height})});if(result.changed)cropDialog.value=false}
const changePlacement=(areaId,figureId,rect)=>execute(document=>updatePlacement(document,areaId,figureId,rect,{canvasWidth:canvasWidth.value}));const restoreNatural=(areaId,figureId)=>execute(document=>restorePlacementNaturalSize(document,areaId,figureId,{canvasWidth:canvasWidth.value}));const removeFigure=(areaId,figureId)=>execute(document=>removeFigurePlacement(document,areaId,figureId));const changeHeight=(areaId,value)=>execute(document=>setImageAreaHeight(document,areaId,value,{canvasWidth:canvasWidth.value}));const moveArea=(areaId,target)=>execute(document=>moveBlockToSection(document,activeSection.value,areaId,target));const removeArea=async(areaId)=>{try{await ElMessageBox.confirm('删除图片区及其中配图？','确认',{type:'warning'});execute(document=>deleteImageArea(document,areaId))}catch{}}
const parseErrors=(error)=>{const detail=error.response?.data?.detail;if(Array.isArray(detail?.errors))return detail.errors;if(Array.isArray(detail))return detail.map(item=>({code:'request_validation',field:item.loc?.join('.'),message:item.msg||'请求格式无效'}));return[]}
const saveDocument=async()=>{flushTextGesture();if(!canSave.value)return;saving.value=true;saveError.value='';serverErrors.value=[];try{const response=await axios.put(`${API_V1_BASE_URL}/questions/${questionId.value}/document`,buildQuestionDocumentPayload(draft.value,revisionNo.value));figureRegistry.dispose();applyDocument(response.data.question);revisionNo.value=response.data.current_revision_no;saving.value=false;ElMessage.success('题目已保存');await router.push({path:'/',query:returnQuery.value})}catch(error){serverErrors.value=parseErrors(error);if(error.response?.status===409){conflict.value=true;saveError.value='版本冲突：本地草稿已完整保留。'}else saveError.value=error.response?.data?.detail?.message||'保存题目失败'}finally{saving.value=false}}
const navigateError=async(error)=>{if(error.section)activeSection.value=error.section;await nextTick();const element=error.block_id&&document.querySelector(`[data-block-id="${CSS.escape(error.block_id)}"]`);element?.scrollIntoView({behavior:'smooth',block:'center'})}
const confirmDiscard=async()=>{flushTextGesture();if(!dirty.value)return true;try{await ElMessageBox.confirm('存在未保存修改，确认放弃吗？','未保存的修改',{confirmButtonText:'放弃修改',cancelButtonText:'继续编辑',type:'warning'});return true}catch{return false}};const discard=async()=>{if(await confirmDiscard()){session.value=resetEditorSession(baseline.value);serverErrors.value=[];syncFigures()}};const reloadLatest=async()=>{if(await confirmDiscard()){figureRegistry.dispose();loadDocument()}};const returnQuery=computed(()=>({tab:'bank',bank_q:route.query.bank_q||undefined,bank_question_id:route.query.bank_question_id||String(questionId.value)}));const goBack=()=>router.push({path:'/',query:returnQuery.value});const beforeUnload=(event)=>{flushTextGesture();if(dirty.value){event.preventDefault();event.returnValue=''}};const keydown=(event)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'&&!['TEXTAREA','INPUT'].includes(document.activeElement?.tagName)){event.preventDefault();event.shiftKey?redo():undo()}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='y'&&!['TEXTAREA','INPUT'].includes(document.activeElement?.tagName)){event.preventDefault();redo()}}
onBeforeRouteLeave(async()=>saving.value?false:confirmDiscard());onMounted(()=>{window.addEventListener('beforeunload',beforeUnload);window.addEventListener('keydown',keydown);loadDocument()});onBeforeUnmount(()=>{generation+=1;window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('keydown',keydown);loader.dispose();figureRegistry.dispose()});watch(()=>route.params.id,()=>{figureRegistry.dispose();loadDocument()});watch(sourceImageUrl,()=>nextTick(syncFigures));watch(()=>draft.value?.figures,()=>nextTick(syncFigures),{deep:true})
</script>
<style scoped>
.question-editor-page{min-height:100vh;padding:16px;background:#f5f7fa}.editor-header{position:sticky;top:0;z-index:5;display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px;background:white;border-bottom:1px solid #dcdfe6}.editor-header>div{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.editor-layout{display:grid;grid-template-columns:minmax(280px,30%) minmax(420px,1fr) minmax(300px,32%);gap:16px;margin-top:16px}.source-pane,.content-pane,.preview-pane{min-width:0;padding:16px;background:white;border-radius:10px}.source-pane,.preview-pane{max-height:calc(100vh - 100px);overflow:auto}.source-image{display:block;width:100%;height:auto}.metadata-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px}.block-list{display:flex;flex-direction:column;gap:8px}.block-card{padding:14px;border:1px solid #dcdfe6;border-radius:8px}.block-head,.block-actions,.paragraph-actions,.insertion{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:10px}.block-head{justify-content:space-between}.block-preview{margin-top:12px;padding:12px;background:#f5f7fa}.insertion{justify-content:center;margin:8px 0}.mobile-switch{display:none;margin-top:12px}.empty-section{padding:12px}@media(max-width:1250px){.editor-layout{grid-template-columns:minmax(280px,36%) minmax(0,1fr)}.preview-pane{grid-column:1/-1;max-height:none}}@media(max-width:980px){.mobile-switch{display:flex}.editor-layout{display:block}.mobile-hidden{display:none}.metadata-grid{grid-template-columns:1fr}.source-pane,.content-pane,.preview-pane{margin-top:12px;max-height:none}.editor-header{position:static}}
</style>
